import type { AppDefinition } from "./definitions";
import { appHostname, type AppRoute, type PlatformSettings } from "./settings";
import { tunnelCredentialsPath } from "./state";
import { renderMeshPolicy } from "./mesh-policy";
import type { MeshMember } from "./directory";
import { getTunnelProvider } from "./tunnel-providers";

type ComposeService = {
  image: string;
  restart: string;
  environment?: Record<string, string>;
  depends_on?: string[];
  volumes?: string[];
  networks: string[];
  command?: string[];
  security_opt: string[];
};

export type DeploymentPlan = {
  apiVersion: "deployment.kimono.dev/v1alpha1";
  runtime: { id: "server"; engine: "docker-compose" };
  compose: {
    name: string;
    services: Record<string, ComposeService>;
    volumes: Record<string, Record<string, never>>;
    networks: Record<string, { internal?: boolean }>;
  };
  files: Record<string, string>;
  providerActions: Array<{ provider: string; tunnelId: string; mode: "token" | "credentials"; tunnelUuid: string; originCertificate: string; hostname: string; path: string; target: string }>;
  secrets: string[];
  warnings: string[];
};

function serviceName(appId: string, serviceId: string) { return `${appId}-${serviceId}`; }
function secretName(appId: string, key: string) { return `KIMONO_SECRET_${appId}_${key}`.toUpperCase().replaceAll("-", "_"); }
function secretReference(appId: string, key: string) { return `\${${secretName(appId, key)}}`; }

function resolveTemplate(template: string, context: { appId: string; hostname: string; configuration: Record<string, string>; services: Set<string> }) {
  return template.replace(/\{\{(hostname|config\.[A-Z0-9_]+|secret\.[A-Z0-9_]+|service\.[a-z0-9-]+)\}\}/g, (_, token: string) => {
    if (token === "hostname") return context.hostname;
    const [kind, key] = token.split(".");
    if (kind === "config") return context.configuration[key] ?? "";
    if (kind === "secret") return secretReference(context.appId, key);
    if (kind === "service" && context.services.has(key)) return serviceName(context.appId, key);
    return "";
  });
}

function endpointFor(route: AppRoute, definition: AppDefinition) {
  for (const service of definition.spec.services) if (service.endpoint?.id === route.endpointId) return { service, endpoint: service.endpoint };
  return null;
}

function cloudflareIngress(tunnelId: string, credentialFile: string, routes: Array<{ hostname: string; path: string; target: string }>) {
  const lines = [`tunnel: ${tunnelId}`, "credentials-file: /etc/cloudflared/credentials.json", "ingress:"];
  for (const route of routes) {
    lines.push(`  - hostname: ${route.hostname}`);
    if (route.path !== "/*") lines.push(`    path: ${route.path}`);
    lines.push(`    service: ${route.target}`);
  }
  lines.push("  - service: http_status:404", "");
  return { contents: lines.join("\n"), credentialFile };
}

function oidcEnvironment(appId: string, identityDomain: string, hostname: string) {
  const issuer = `https://${identityDomain}/application/o`;
  return {
    OIDC_CLIENT_ID: `kimono-${appId}`,
    OIDC_CLIENT_SECRET: secretReference(appId, "OIDC_CLIENT_SECRET"),
    OIDC_AUTH_URI: `${issuer}/authorize/`,
    OIDC_TOKEN_URI: `${issuer}/token/`,
    OIDC_USERINFO_URI: `${issuer}/userinfo/`,
    OIDC_LOGOUT_URI: `${issuer}/kimono-${appId}/end-session/`,
    OIDC_USERNAME_CLAIM: "preferred_username",
    OIDC_DISPLAY_NAME: "Kimono",
    OIDC_SCOPES: "openid profile email",
    FORCE_HTTPS: "true",
    URL: `https://${hostname}`,
  } satisfies Record<string, string>;
}

/**
 * Authentik reads blueprints from a mounted directory. The reconciler expands the
 * secret placeholder when it writes the file so that the plan carries no values.
 */
function authentikBlueprint(app: { id: string; name: string }, hostname: string, colors: readonly string[]) {
  const slug = `kimono-${app.id}`;
  return `# Generated by Kimono. Do not edit; change the app in the Admin portal.
version: 1
metadata:
  name: ${app.name}
  labels:
    blueprints.goauthentik.io/description: OIDC provider and application for ${app.name}
    blueprints.goauthentik.io/instantiate: "true"

entries:
  - id: ${slug}-provider
    model: authentik_providers_oauth2.oauth2provider
    state: present
    identifiers:
      client_id: ${slug}
    attrs:
      name: ${app.name}
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      client_type: confidential
      # Without a signing key Authentik signs the ID token HS256 with the client
      # secret and publishes an empty JWKS, which every RS256 client rejects.
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      client_secret: \${${secretName(app.id, "OIDC_CLIENT_SECRET")}}
      grant_types:
        - authorization_code
        - refresh_token
      include_claims_in_id_token: true
      issuer_mode: per_provider
      sub_mode: user_uuid
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
      redirect_uris:
        - url: https://${hostname}/auth/oidc.callback
          matching_mode: strict

  - model: authentik_core.application
    state: present
    identifiers:
      slug: ${slug}
    attrs:
      name: ${app.name}
      provider: !KeyOf ${slug}-provider
      meta_launch_url: https://${hostname}
      meta_description: Provisioned by Kimono
      policy_engine_mode: any
      attributes:
        kimono_colors: "${colors.join(",")}"
`;
}

export function renderDeploymentPlan(settings: PlatformSettings, definitions: AppDefinition[], meshMembers: Record<string, MeshMember> = {}): DeploymentPlan {
  const definitionById = new Map(definitions.map((definition) => [definition.metadata.id, definition]));
  const plan: DeploymentPlan = {
    apiVersion: "deployment.kimono.dev/v1alpha1",
    runtime: { id: "server", engine: "docker-compose" },
    compose: { name: "kimono-apps", services: {}, volumes: {}, networks: { "kimono-edge": {} } },
    files: {}, providerActions: [], secrets: [], warnings: [],
  };

  for (const app of Object.values(settings.apps).filter((item) => item.enabled && item.definitionId !== "kimono-portal")) {
    const definition = definitionById.get(app.definitionId);
    if (!definition) { plan.warnings.push(`${app.name}: definition ${app.definitionId} is unavailable`); continue; }
    const privateNetwork = `${app.id}-private`;
    plan.compose.networks[privateNetwork] = { internal: !app.networkPolicy.internetAccess };
    const appRoutes = Object.values(settings.routes).filter((route) => route.enabled && route.appId === app.id);
    const routedServices = new Set(appRoutes.map((route) => endpointFor(route, definition)?.service.id).filter((id): id is string => Boolean(id)));
    const configuration = Object.fromEntries(definition.spec.configuration.map((field) => [field.key, app.environment[field.key]?.value ?? field.default ?? ""]));
    const services = new Set(definition.spec.services.map((service) => service.id));
    const hostname = appHostname(app.domain, settings.baseDomain);

    for (const service of definition.spec.services) {
      const name = serviceName(app.id, service.id);
      const volumes = definition.spec.volumes.filter((volume) => volume.service === service.id).map((volume) => {
        const volumeName = `${app.id}-${volume.id}`;
        plan.compose.volumes[volumeName] = {};
        return `${volumeName}:${volume.path}`;
      });
      const environment = Object.fromEntries(Object.entries(service.environment || {}).map(([key, value]) => [key, resolveTemplate(value, { appId: app.id, hostname, configuration, services })]));
      if (service.endpoint) {
        for (const field of definition.spec.configuration) {
          const override = app.environment[field.key];
          const value = override?.value ?? field.default;
          if (value && !(field.key in environment)) environment[field.key] = override?.secret ? secretReference(app.id, field.key) : value;
        }
      }
      if (service.endpoint && routedServices.has(service.id) && definition.spec.integration === "connected") {
        if (settings.identityDomain) Object.assign(environment, oidcEnvironment(app.id, settings.identityDomain, hostname));
        else plan.warnings.push(`${app.name}: identity domain is unknown, so single sign-on was not configured`);
      }
      plan.compose.services[name] = {
        image: service.image,
        restart: "unless-stopped",
        ...(Object.keys(environment).length ? { environment } : {}),
        ...(service.dependsOn?.length ? { depends_on: service.dependsOn.map((dependency) => serviceName(app.id, dependency)) } : {}),
        ...(volumes.length ? { volumes } : {}),
        networks: routedServices.has(service.id) ? [privateNetwork, "kimono-edge"] : [privateNetwork],
        security_opt: ["no-new-privileges:true"],
      };
    }

    if (definition.spec.integration === "connected" && settings.identityDomain && routedServices.size) {
      plan.files[`authentik/kimono-${app.id}.yaml`] = authentikBlueprint(app, hostname, app.colors);
    }
  }

  for (const tunnel of Object.values(settings.tunnels).filter((item) => item.enabled)) {
    const routes = Object.values(settings.routes).filter((route) => route.enabled && route.tunnelId === tunnel.id).flatMap((route) => {
      const app = settings.apps[route.appId];
      const definition = app ? definitionById.get(app.definitionId) : undefined;
      const endpoint = definition ? endpointFor(route, definition) : null;
      if (!app || !endpoint) { plan.warnings.push(`${route.id}: target endpoint is unavailable in the server runtime`); return []; }
      return [{ hostname: route.hostname, path: route.path, target: `${endpoint.endpoint.protocol}://${serviceName(app.id, endpoint.service.id)}:${endpoint.endpoint.port}` }];
    });
    const provider = getTunnelProvider(tunnel.provider);
    if (!provider) { plan.warnings.push(`${tunnel.name}: provider ${tunnel.provider} is not installed`); continue; }
    if (provider.id !== "cloudflare") { plan.warnings.push(`${tunnel.name}: provider ${tunnel.provider} has no renderer`); continue; }
    const token = tunnel.configuration.TUNNEL_TOKEN;
    const tunnelId = tunnel.configuration.TUNNEL_ID?.value;
    const credentialFile = tunnel.configuration.CREDENTIALS_FILE?.value;
    const name = `tunnel-${tunnel.id}`;
    const originCertificate = tunnel.configuration.ORIGIN_CERTIFICATE?.value || "";
    if (token) {
      plan.compose.services[name] = { image: provider.connectorImage, restart: "unless-stopped", environment: { TUNNEL_TOKEN: secretReference(`tunnel-${tunnel.id}`, "TOKEN") }, command: ["tunnel", "--no-autoupdate", "run"], networks: ["kimono-edge"], security_opt: ["no-new-privileges:true"] };
      for (const route of routes) plan.providerActions.push({ provider: "cloudflare", tunnelId: tunnel.id, mode: "token", tunnelUuid: tunnelId || "", originCertificate, ...route });
    } else if (tunnelId && credentialFile) {
      const ingress = cloudflareIngress(tunnelId, credentialFile, routes);
      const configPath = `generated/cloudflare-${tunnel.id}.yml`;
      plan.files[configPath] = ingress.contents;
      plan.compose.services[name] = { image: provider.connectorImage, restart: "unless-stopped", command: ["tunnel", "--config", "/etc/cloudflared/config.yml", "run"], volumes: [`./${configPath}:/etc/cloudflared/config.yml:ro`, `${tunnelCredentialsPath(tunnel.id)}:/etc/cloudflared/credentials.json:ro`], networks: ["kimono-edge"], security_opt: ["no-new-privileges:true"] };
      // A credentials-mode connector still needs a CNAME per hostname before Cloudflare will route to it.
      if (originCertificate) for (const route of routes) plan.providerActions.push({ provider: "cloudflare", tunnelId: tunnel.id, mode: "credentials", tunnelUuid: tunnelId, originCertificate, ...route });
      else plan.warnings.push(`${tunnel.name}: no origin certificate, so DNS records cannot be created automatically`);
    } else plan.warnings.push(`${tunnel.name}: credentials are incomplete`);
  }

  plan.secrets = collectSecretNames(plan);
  // The mesh policy is desired state like everything else: the Portal renders
  // it, the reconciler installs it and asks Headscale to reload.
  plan.files["mesh/policy.hujson"] = renderMeshPolicy(meshMembers);

  return plan;
}

const referencePattern = /\$\{(KIMONO_SECRET_[A-Z0-9_]+)\}/g;

function collectSecretNames(plan: DeploymentPlan) {
  const names = new Set<string>();
  const scan = (value: string) => { for (const match of value.matchAll(referencePattern)) names.add(match[1]); };
  for (const service of Object.values(plan.compose.services)) for (const value of Object.values(service.environment || {})) scan(value);
  for (const contents of Object.values(plan.files)) scan(contents);
  return [...names].sort();
}
