import type { AppDefinition, ConfigurationField } from "./definitions";
import { appHostname, type AppRoute, type PlatformSettings } from "./settings";
import { tunnelCredentialsPath } from "./state";
import { renderMeshPolicy } from "./mesh-policy";
import type { MeshMember } from "./directory";
import { getTunnelProvider } from "./tunnel-providers";

type ComposeService = {
  image: string;
  restart: string;
  environment?: Record<string, string>;
  depends_on?: string[];
  volumes?: string[];
  networks: string[];
  command?: string[];
  security_opt: string[];
};

export type DeploymentPlan = {
  apiVersion: "deployment.kimono.dev/v1alpha1";
  runtime: { id: "server"; engine: "docker-compose" };
  compose: {
    name: string;
    services: Record<string, ComposeService>;
    volumes: Record<string, Record<string, never>>;
    networks: Record<string, { internal?: boolean }>;
  };
  files: Record<string, string>;
  providerActions: Array<{ provider: string; tunnelId: string; mode: "token" | "credentials" | "cname"; tunnelUuid: string; originCertificate: string; hostname: string; path: string; target: string; cname: string }>;
  secrets: string[];
  warnings: string[];
};

function serviceName(appId: string, serviceId: string) { return `${appId}-${serviceId}`; }
function secretName(appId: string, key: string) { return `KIMONO_SECRET_${appId}_${key}`.toUpperCase().replaceAll("-", "_"); }
function secretReference(appId: string, key: string) { return `\${${secretName(appId, key)}}`; }

type TemplateContext = {
  appId: string;
  hostname: string;
  configuration: Record<string, string>;
  fields: Map<string, ConfigurationField>;
  services: Set<string>;
  oidc?: Record<string, string>;
};

const tokenPattern = /\{\{(hostname|config\.[A-Z0-9_]+|secret\.[A-Z0-9_]+|service\.[a-z0-9-]+|oidc\.[a-zA-Z]+)\}\}/g;

function resolveTemplate(template: string, context: TemplateContext) {
  return template.replace(tokenPattern, (_, token: string) => {
    if (token === "hostname") return context.hostname;
    const [kind, key] = token.split(".");
    if (kind === "config") return context.configuration[key] ?? "";
    if (kind === "secret") return secretReference(context.appId, key);
    if (kind === "service" && context.services.has(key)) return serviceName(context.appId, key);
    if (kind === "oidc") return context.oidc?.[key] ?? "";
    return "";
  });
}

/**
 * A settings document is typed JSON, not text: a value that is nothing but one
 * token takes the token's own type, so a toggle becomes true and a number
 * becomes a number. Anything else is substituted as text.
 */
function resolveValue(value: string, context: TemplateContext): unknown {
  const single = /^\{\{([^{}]+)\}\}$/.exec(value);
  const token = single?.[1];
  if (!token) return resolveTemplate(value, context);
  if (token === "oidc.configured") return Boolean(context.oidc);
  const [kind, key] = token.split(".");
  if (kind !== "config") return resolveTemplate(value, context);
  const field = context.fields.get(key);
  const raw = context.configuration[key] ?? "";
  // A secret keeps travelling by reference, so no plan ever carries its value.
  if (field?.kind === "secret") return raw ? secretReference(context.appId, key) : "";
  if (field?.kind === "toggle") return raw === "on";
  if (field?.kind === "number" || field?.kind === "bytes") return raw === "" ? null : Number(raw);
  return raw;
}

/** Resolves every string leaf of a definition-supplied document. */
function resolveDocument(value: unknown, context: TemplateContext): unknown {
  if (typeof value === "string") return resolveValue(value, context);
  if (Array.isArray(value)) return value.map((item) => resolveDocument(item, context));
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, resolveDocument(item, context)]));
  return value;
}

function endpointFor(route: AppRoute, definition: AppDefinition) {
  for (const service of definition.spec.services) if (service.endpoint?.id === route.endpointId) return { service, endpoint: service.endpoint };
  return null;
}

/**
 * A site block per published hostname. The appliance's own proxy serves these,
 * so the upstream is the app container on the shared edge network.
 */
function caddySites(routes: Array<{ hostname: string; target: string }>) {
  const lines = ["# Generated by Kimono. Do not edit; change the app in the Admin portal."];
  for (const route of routes) {
    lines.push(`${route.hostname} {`, "\tencode zstd gzip", `\treverse_proxy ${route.target.replace(/^https?:\/\//, "")}`, "}", "");
  }
  return lines.join("\n");
}

function cloudflareIngress(tunnelId: string, credentialFile: string, routes: Array<{ hostname: string; path: string; target: string }>) {
  const lines = [`tunnel: ${tunnelId}`, "credentials-file: /etc/cloudflared/credentials.json", "ingress:"];
  for (const route of routes) {
    lines.push(`  - hostname: ${route.hostname}`);
    if (route.path !== "/*") lines.push(`    path: ${route.path}`);
    lines.push(`    service: ${route.target}`);
  }
  lines.push("  - service: http_status:404", "");
  return { contents: lines.join("\n"), credentialFile };
}

/**
 * Everything Kimono knows about an app's provider, as `{{oidc.*}}` tokens. The
 * provider is issued per app, so its issuer carries the app's own slug.
 */
function oidcValues(appId: string, identityDomain: string, hostname: string) {
  const clientId = `kimono-${appId}`;
  const endpoint = `https://${identityDomain}/application/o`;
  return {
    clientId,
    clientSecret: secretReference(appId, "OIDC_CLIENT_SECRET"),
    baseUrl: `https://${identityDomain}`,
    issuer: `${endpoint}/${clientId}/`,
    authorize: `${endpoint}/authorize/`,
    token: `${endpoint}/token/`,
    userinfo: `${endpoint}/userinfo/`,
    endSession: `${endpoint}/${clientId}/end-session/`,
    url: `https://${hostname}`,
  } satisfies Record<string, string>;
}

/** The variable names Outline established, used by any app that does not name its own. */
function oidcEnvironment(oidc: ReturnType<typeof oidcValues>) {
  return {
    OIDC_CLIENT_ID: oidc.clientId,
    OIDC_CLIENT_SECRET: oidc.clientSecret,
    OIDC_AUTH_URI: oidc.authorize,
    OIDC_TOKEN_URI: oidc.token,
    OIDC_USERINFO_URI: oidc.userinfo,
    OIDC_LOGOUT_URI: oidc.endSession,
    OIDC_USERNAME_CLAIM: "preferred_username",
    OIDC_DISPLAY_NAME: "Kimono",
    OIDC_SCOPES: "openid profile email",
    FORCE_HTTPS: "true",
    URL: oidc.url,
  } satisfies Record<string, string>;
}

/**
 * Authentik reads blueprints from a mounted directory. The reconciler expands the
 * secret placeholder when it writes the file so that the plan carries no values.
 */
function authentikBlueprint(app: { id: string; name: string }, hostname: string, colors: readonly string[], redirectUris: readonly string[]) {
  const slug = `kimono-${app.id}`;
  const redirects = redirectUris.map((uri) => `        - url: ${uri}\n          matching_mode: strict`).join("\n");
  return `# Generated by Kimono. Do not edit; change the app in the Admin portal.
version: 1
metadata:
  name: ${app.name}
  labels:
    blueprints.goauthentik.io/description: OIDC provider and application for ${app.name}
    blueprints.goauthentik.io/instantiate: "true"

entries:
  - id: ${slug}-provider
    model: authentik_providers_oauth2.oauth2provider
    state: present
    identifiers:
      client_id: ${slug}
    attrs:
      name: ${app.name}
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      client_type: confidential
      # Without a signing key Authentik signs the ID token HS256 with the client
      # secret and publishes an empty JWKS, which every RS256 client rejects.
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      client_secret: \${${secretName(app.id, "OIDC_CLIENT_SECRET")}}
      grant_types:
        - authorization_code
        - refresh_token
      include_claims_in_id_token: true
      issuer_mode: per_provider
      sub_mode: user_uuid
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
      redirect_uris:
${redirects}

  - model: authentik_core.application
    state: present
    identifiers:
      slug: ${slug}
    attrs:
      name: ${app.name}
      provider: !KeyOf ${slug}-provider
      meta_launch_url: https://${hostname}
      meta_description: Provisioned by Kimono
      policy_engine_mode: any
      attributes:
        kimono_colors: "${colors.join(",")}"
`;
}

export function renderDeploymentPlan(settings: PlatformSettings, definitions: AppDefinition[], meshMembers: Record<string, MeshMember> = {}): DeploymentPlan {
  const definitionById = new Map(definitions.map((definition) => [definition.metadata.id, definition]));
  const plan: DeploymentPlan = {
    apiVersion: "deployment.kimono.dev/v1alpha1",
    runtime: { id: "server", engine: "docker-compose" },
    compose: { name: "kimono-apps", services: {}, volumes: {}, networks: { "kimono-edge": {} } },
    files: {}, providerActions: [], secrets: [], warnings: [],
  };

  for (const app of Object.values(settings.apps).filter((item) => item.enabled && item.definitionId !== "kimono-portal")) {
    const definition = definitionById.get(app.definitionId);
    if (!definition) { plan.warnings.push(`${app.name}: definition ${app.definitionId} is unavailable`); continue; }
    const privateNetwork = `${app.id}-private`;
    plan.compose.networks[privateNetwork] = { internal: !app.networkPolicy.internetAccess };
    const appRoutes = Object.values(settings.routes).filter((route) => route.enabled && route.appId === app.id);
    const routedServices = new Set(appRoutes.map((route) => endpointFor(route, definition)?.service.id).filter((id): id is string => Boolean(id)));
    const configuration = Object.fromEntries(definition.spec.configuration.map((field) => [field.key, app.environment[field.key]?.value ?? field.default ?? ""]));
    const services = new Set(definition.spec.services.map((service) => service.id));
    const hostname = appHostname(app.domain, settings.baseDomain);
    const fields = new Map(definition.spec.configuration.map((field) => [field.key, field]));
    const identity = definition.spec.identity;
    const oidc = settings.identityDomain ? oidcValues(app.id, settings.identityDomain, hostname) : null;
    const context: TemplateContext = { appId: app.id, hostname, configuration, fields, services, ...(oidc ? { oidc } : {}) };

    for (const service of definition.spec.services) {
      const name = serviceName(app.id, service.id);
      const volumes = definition.spec.volumes.filter((volume) => volume.service === service.id).map((volume) => {
        const volumeName = `${app.id}-${volume.id}`;
        plan.compose.volumes[volumeName] = {};
        return `${volumeName}:${volume.path}`;
      });
      const environment = Object.fromEntries(Object.entries(service.environment || {}).map(([key, value]) => [key, resolveTemplate(value, context)]));
      if (service.endpoint) {
        for (const field of definition.spec.configuration) {
          if (field.target === "settings") continue;
          const override = app.environment[field.key];
          const value = override?.value ?? field.default;
          if (value && !(field.key in environment)) environment[field.key] = override?.secret ? secretReference(app.id, field.key) : value;
        }
      }
      if (service.endpoint && routedServices.has(service.id) && definition.spec.integration === "connected") {
        if (!oidc) plan.warnings.push(`${app.name}: identity domain is unknown, so single sign-on was not configured`);
        // An app that names its own variables gets those; an app that reads
        // identity from its settings document gets none here; everyone else
        // gets the variable names Outline established.
        else if (identity?.delivery !== "settings") {
          Object.assign(environment, identity?.environment
            ? Object.fromEntries(Object.entries(identity.environment).map(([key, value]) => [key, resolveTemplate(value, context)]))
            : oidcEnvironment(oidc));
        }
      }
      // An app that keeps its configuration in a file gets one rendered beside
      // the Compose project and mounted read-only. It is desired state like
      // every environment variable: the Admin portal remains the only editor.
      const settingsFile = definition.spec.settingsFile;
      if (settingsFile && settingsFile.service === service.id) {
        const path = `apps/${app.id}-settings.json`;
        plan.files[path] = `${JSON.stringify(resolveDocument(settingsFile.document, context), null, 2)}\n`;
        volumes.push(`./${path}:${settingsFile.path}:ro`);
      }
      plan.compose.services[name] = {
        image: service.image,
        restart: "unless-stopped",
        ...(Object.keys(environment).length ? { environment } : {}),
        ...(service.dependsOn?.length ? { depends_on: service.dependsOn.map((dependency) => serviceName(app.id, dependency)) } : {}),
        ...(volumes.length ? { volumes } : {}),
        networks: routedServices.has(service.id) ? [privateNetwork, "kimono-edge"] : [privateNetwork],
        security_opt: ["no-new-privileges:true"],
      };
    }

    if (definition.spec.integration === "connected" && oidc && routedServices.size) {
      const redirectUris = (identity?.redirectUris || []).map((uri) => resolveTemplate(uri, context));
      plan.files[`authentik/kimono-${app.id}.yaml`] = authentikBlueprint(app, hostname, app.colors, redirectUris);
    }
  }

  // Directly published names point at the address the Portal already answers on,
  // read from its own instance rather than assumed: the Portal's hostname is an
  // administrator's choice and is often neither "kimono" nor a subdomain at all.
  const portal = settings.apps["kimono-portal"];
  const portalHostname = portal ? appHostname(portal.domain, settings.baseDomain) : "";

  for (const tunnel of Object.values(settings.tunnels).filter((item) => item.enabled)) {
    const routes = Object.values(settings.routes).filter((route) => route.enabled && route.tunnelId === tunnel.id).flatMap((route) => {
      const app = settings.apps[route.appId];
      const definition = app ? definitionById.get(app.definitionId) : undefined;
      const endpoint = definition ? endpointFor(route, definition) : null;
      if (!app || !endpoint) { plan.warnings.push(`${route.id}: target endpoint is unavailable in the server runtime`); return []; }
      return [{ hostname: route.hostname, path: route.path, target: `${endpoint.endpoint.protocol}://${serviceName(app.id, endpoint.service.id)}:${endpoint.endpoint.port}` }];
    });
    const provider = getTunnelProvider(tunnel.provider);
    if (!provider) { plan.warnings.push(`${tunnel.name}: provider ${tunnel.provider} is not installed`); continue; }
    // An exposure with no connector is served by the appliance's own proxy: its
    // hostnames become Caddy sites and CNAME to whatever address the Portal
    // already answers on, which Dynamic DNS keeps current.
    if (provider.id === "direct") {
      if (!routes.length) continue;
      if (!portalHostname) { plan.warnings.push(`${tunnel.name}: the Portal has no hostname, so there is nothing to point these names at`); continue; }
      plan.files[`generated/caddy-${tunnel.id}.caddy`] = caddySites(routes);
      for (const route of routes) plan.providerActions.push({ provider: "direct", tunnelId: tunnel.id, mode: "cname", tunnelUuid: "", originCertificate: "", cname: portalHostname, ...route });
      continue;
    }
    if (provider.id !== "cloudflare") { plan.warnings.push(`${tunnel.name}: provider ${tunnel.provider} has no renderer`); continue; }
    const token = tunnel.configuration.TUNNEL_TOKEN;
    const tunnelId = tunnel.configuration.TUNNEL_ID?.value;
    const credentialFile = tunnel.configuration.CREDENTIALS_FILE?.value;
    const name = `tunnel-${tunnel.id}`;
    const originCertificate = tunnel.configuration.ORIGIN_CERTIFICATE?.value || "";
    if (token) {
      plan.compose.services[name] = { image: provider.connectorImage, restart: "unless-stopped", environment: { TUNNEL_TOKEN: secretReference(`tunnel-${tunnel.id}`, "TOKEN") }, command: ["tunnel", "--no-autoupdate", "run"], networks: ["kimono-edge"], security_opt: ["no-new-privileges:true"] };
      for (const route of routes) plan.providerActions.push({ provider: "cloudflare", tunnelId: tunnel.id, mode: "token", tunnelUuid: tunnelId || "", originCertificate, cname: "", ...route });
    } else if (tunnelId && credentialFile) {
      const ingress = cloudflareIngress(tunnelId, credentialFile, routes);
      const configPath = `generated/cloudflare-${tunnel.id}.yml`;
      plan.files[configPath] = ingress.contents;
      plan.compose.services[name] = { image: provider.connectorImage, restart: "unless-stopped", command: ["tunnel", "--config", "/etc/cloudflared/config.yml", "run"], volumes: [`./${configPath}:/etc/cloudflared/config.yml:ro`, `${tunnelCredentialsPath(tunnel.id)}:/etc/cloudflared/credentials.json:ro`], networks: ["kimono-edge"], security_opt: ["no-new-privileges:true"] };
      // A credentials-mode connector still needs a CNAME per hostname before Cloudflare will route to it.
      if (originCertificate) for (const route of routes) plan.providerActions.push({ provider: "cloudflare", tunnelId: tunnel.id, mode: "credentials", tunnelUuid: tunnelId, originCertificate, cname: "", ...route });
      else plan.warnings.push(`${tunnel.name}: no origin certificate, so DNS records cannot be created automatically`);
    } else plan.warnings.push(`${tunnel.name}: credentials are incomplete`);
  }

  plan.secrets = collectSecretNames(plan);
  // The mesh policy is desired state like everything else: the Portal renders
  // it, the reconciler installs it and asks Headscale to reload.
  plan.files["mesh/policy.hujson"] = renderMeshPolicy(meshMembers);

  return plan;
}

const referencePattern = /\$\{(KIMONO_SECRET_[A-Z0-9_]+)\}/g;

function collectSecretNames(plan: DeploymentPlan) {
  const names = new Set<string>();
  const scan = (value: string) => { for (const match of value.matchAll(referencePattern)) names.add(match[1]); };
  for (const service of Object.values(plan.compose.services)) for (const value of Object.values(service.environment || {})) scan(value);
  for (const contents of Object.values(plan.files)) scan(contents);
  return [...names].sort();
}
