package reconcile

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Layout describes where the reconciler materializes a plan.
type Layout struct {
	ProjectDir   string // Compose project and generated provider files
	BlueprintDir string // Identity blueprints, mounted into Authentik
	MeshDir      string // Headscale policy, rendered into its config volume
}

func (l Layout) ComposePath() string     { return filepath.Join(l.ProjectDir, "compose.yaml") }
func (l Layout) EnvironmentPath() string { return filepath.Join(l.ProjectDir, ".env") }

func scalar(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(encoded)
}

// composeValue escapes literal dollars so Compose interpolation only resolves
// the secret references the Portal deliberately emitted.
func composeValue(value string) string {
	var builder strings.Builder
	for index := 0; index < len(value); index++ {
		if value[index] == '$' && !strings.HasPrefix(value[index:], "${KIMONO_SECRET_") {
			builder.WriteString("$$")
			continue
		}
		builder.WriteByte(value[index])
	}
	return builder.String()
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// RenderCompose emits the Compose document for a plan. Output is deterministic
// so that an unchanged plan produces a byte-identical file.
func RenderCompose(plan Plan) string {
	var builder strings.Builder
	builder.WriteString("# Generated by Kimono from the Portal deployment plan. Do not edit.\n")
	fmt.Fprintf(&builder, "name: %s\n\nservices:\n", plan.Compose.Name)
	for _, name := range sortedKeys(plan.Compose.Services) {
		service := plan.Compose.Services[name]
		fmt.Fprintf(&builder, "  %s:\n    image: %s\n    restart: %s\n", name, scalar(service.Image), scalar(service.Restart))
		if len(service.Environment) > 0 {
			builder.WriteString("    environment:\n")
			for _, key := range sortedKeys(service.Environment) {
				fmt.Fprintf(&builder, "      %s: %s\n", key, scalar(composeValue(service.Environment[key])))
			}
		}
		writeList(&builder, "command", service.Command)
		writeList(&builder, "depends_on", service.DependsOn)
		writeList(&builder, "volumes", service.Volumes)
		writeList(&builder, "networks", service.Networks)
		writeList(&builder, "security_opt", service.SecurityOpt)
	}
	builder.WriteString("\nvolumes:\n")
	for _, name := range sortedKeys(plan.Compose.Volumes) {
		fmt.Fprintf(&builder, "  %s: {}\n", name)
	}
	builder.WriteString("\nnetworks:\n")
	for _, name := range sortedKeys(plan.Compose.Networks) {
		// The appliance owns the edge network so its proxy can serve a hostname
		// published without a tunnel. This project attaches rather than creates.
		if name == EdgeNetwork {
			fmt.Fprintf(&builder, "  %s:\n    name: %s\n    external: true\n", name, name)
			continue
		}
		if plan.Compose.Networks[name].Internal {
			fmt.Fprintf(&builder, "  %s:\n    internal: true\n", name)
			continue
		}
		fmt.Fprintf(&builder, "  %s: {}\n", name)
	}
	return builder.String()
}

func writeList(builder *strings.Builder, field string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(builder, "    %s:\n", field)
	for _, value := range values {
		fmt.Fprintf(builder, "      - %s\n", scalar(value))
	}
}

func writeFileIfChanged(path string, contents string, mode os.FileMode) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil && string(existing) == contents {
		// Content is current, but a file written by an earlier release may still
		// carry a mode the consuming container cannot read.
		info, statErr := os.Stat(path)
		if statErr == nil && info.Mode().Perm() != mode.Perm() {
			return false, os.Chmod(path, mode)
		}
		return false, statErr
	}
	temporary := path + ".new"
	if err := os.WriteFile(temporary, []byte(contents), mode); err != nil {
		return false, err
	}
	return true, os.Rename(temporary, path)
}

type RenderResult struct {
	BlueprintsChanged bool
	ComposeChanged    bool
	MeshChanged       bool
	// Blueprints lists every generated blueprint by file name so the caller can
	// hand them to Authentik directly. Discovery does not reach this directory.
	Blueprints []string
	// ChangedFiles lists the generated files a container mounts that this pass
	// rewrote, by plan-relative path. A process reads its configuration once at
	// startup, so whoever mounts one of these is serving a stale copy.
	ChangedFiles []string
}

// Render materializes the Compose file, the environment file, and every
// generated file. Blueprints are routed to the identity blueprint directory;
// everything else stays inside the project directory.
func Render(plan Plan, secrets map[string]string, layout Layout) (RenderResult, error) {
	var result RenderResult
	environment := make([]string, 0, len(plan.Secrets))
	for _, name := range plan.Secrets {
		value, ok := secrets[name]
		if !ok {
			return result, fmt.Errorf("plan references %s but no value was published", name)
		}
		environment = append(environment, name+"="+value)
	}
	sort.Strings(environment)
	if _, err := writeFileIfChanged(layout.EnvironmentPath(), strings.Join(environment, "\n")+"\n", 0600); err != nil {
		return result, err
	}

	known := map[string]bool{}
	for _, file := range sortedKeys(plan.Files) {
		contents, err := ExpandSecrets(plan.Files[file], secrets)
		if err != nil {
			return result, fmt.Errorf("%s: %w", file, err)
		}
		destination := filepath.Join(layout.ProjectDir, file)
		switch {
		case strings.HasPrefix(file, BlueprintPrefix):
			destination = filepath.Join(layout.BlueprintDir, strings.TrimPrefix(file, BlueprintPrefix))
			known[filepath.Base(destination)] = true
			result.Blueprints = append(result.Blueprints, filepath.Base(destination))
		case strings.HasPrefix(file, MeshPrefix):
			if layout.MeshDir == "" {
				continue
			}
			destination = filepath.Join(layout.MeshDir, strings.TrimPrefix(file, MeshPrefix))
		}
		// Blueprints and app identity files carry client secrets and are read by
		// root containers. Connector configuration is hostnames only and is read
		// as nonroot.
		mode := os.FileMode(0644)
		if strings.HasPrefix(file, BlueprintPrefix) || strings.HasPrefix(file, AppPrefix) {
			mode = 0600
		}
		changed, err := writeFileIfChanged(destination, contents, mode)
		if err != nil {
			return result, err
		}
		switch {
		case !changed:
		case strings.HasPrefix(file, BlueprintPrefix):
			result.BlueprintsChanged = true
		case strings.HasPrefix(file, MeshPrefix):
			result.MeshChanged = true
		default:
			result.ChangedFiles = append(result.ChangedFiles, file)
		}
	}
	removed, err := pruneBlueprints(layout.BlueprintDir, known)
	if err != nil {
		return result, err
	}
	result.BlueprintsChanged = result.BlueprintsChanged || removed

	changed, err := writeFileIfChanged(layout.ComposePath(), RenderCompose(plan), 0600)
	if err != nil {
		return result, err
	}
	result.ComposeChanged = changed
	return result, nil
}

// pruneBlueprints removes generated blueprints for apps that no longer exist.
// Only files this reconciler wrote are considered, never checked-in blueprints.
func pruneBlueprints(directory string, known map[string]bool) (bool, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	removed := false
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasPrefix(name, "kimono-") || !strings.HasSuffix(name, ".yaml") || known[name] {
			continue
		}
		contents, err := os.ReadFile(filepath.Join(directory, name))
		if err != nil || !strings.HasPrefix(string(contents), "# Generated by Kimono") {
			continue
		}
		if err := os.Remove(filepath.Join(directory, name)); err != nil {
			return removed, err
		}
		removed = true
	}
	return removed, nil
}
